import Head from 'next/head'
import Link from 'next/link'
import MainPages from './main/main'

export default function Home() {
  return (
    <>
      <Head>
        <title>weAround</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainPages />
      </main>
    </>
  )
}
